name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: 
          - macos-13
          - macos-12
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run build 
        run: bash build/execute.sh 
        shell: bash
