name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ["macos-13", "macos-12", "macos-11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run build 
        run: bash build/execute.sh 
        shell: bash
